name: Build and Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install uv
        uv pip install --system -r requirements.txt

    - name: Run package script
      run: |
        chcp 65001
        pyinstaller --noconfirm --onefile --windowed --icon "resources/images/京东_128x128.ico" --name "京东订单（个人）"  "app.py"