name: Build and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install uv
        uv pip install --system -r requirements.txt
        uv pip install --system pyinstaller

    - name: Build executable
      run: |
        chcp 65001
        pyinstaller --noconfirm --onefile --windowed --icon "resources/images/京东_128x128.ico" --name "京东订单（个人）" "app.py"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/京东订单（个人）.exe
        tag_name: build-${{ github.sha }}
        name: 自动构建 - ${{ github.sha }}
        body: |
          自动构建版本 - ${{ github.sha }}
          提交信息: ${{ github.event.head_commit.message }}
          构建时间: ${{ github.event.head_commit.timestamp }}
          触发者: ${{ github.actor }}
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}